# Generated by Django 3.1.5 on 2021-03-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210320_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='picture/no-img.jpg', upload_to='picture'),
        ),
    ]
