# Generated by Django 3.1.5 on 2021-03-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210320_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id', 'title']},
        ),
    ]
